// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-containers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_containers_default = defineTool({
  name: "list_containers",
  title: "List containers",
  description: "List containers in the signed-in user's organization. Optional filters by status and container number substring.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. 'in_yard', 'gate_out', 'sold'."),
    search: z.string().optional().describe("Optional case-insensitive substring to match against container_number."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("containers").select("id, container_number, iso_type, status, location, condition_grade, owner_customer_id, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (search) q = q.ilike("container_number", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { containers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-container.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_container_default = defineTool2({
  name: "get_container",
  title: "Get container",
  description: "Fetch full details for a single container by container_number.",
  inputSchema: {
    container_number: z2.string().trim().min(1).describe("Container number, e.g. 'MSCU1234567'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ container_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("containers").select("*").eq("container_number", container_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Container not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { container: data }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_customers_default = defineTool3({
  name: "list_customers",
  title: "List customers",
  description: "List customers in the signed-in user's organization. Optional name/email substring search.",
  inputSchema: {
    search: z3.string().optional().describe("Case-insensitive substring to match against name or email."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("customers").select("id, name, email, phone, currency, country, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) q = q.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-movements.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_movements_default = defineTool4({
  name: "list_recent_movements",
  title: "List recent container movements",
  description: "List the most recent container movements (gate-in/out, yard moves) for the signed-in user's organization.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).optional().describe("Max rows (default 50)."),
    movement_type: z4.string().optional().describe("Optional exact movement_type filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, movement_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb4(ctx).from("movements").select("id, container_id, movement_type, from_location, to_location, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (movement_type) q = q.eq("movement_type", movement_type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { movements: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/finance-dashboard.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var finance_dashboard_default = defineTool5({
  name: "get_finance_dashboard",
  title: "Get finance dashboard metrics",
  description: "Return the signed-in user's organization finance KPIs: cash on hand, receivables, payables, MTD P&L (base currency).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("finance_dashboard_metrics").select("*").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { metrics: data ?? {} }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool6({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, and OAuth client id \u2014 useful to verify the connection.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ccvlayjcgwiasblitthp";
var mcp_default = defineMcp({
  name: "cdms-mcp",
  title: "Port Pal CDMS",
  version: "0.1.0",
  instructions: "Tools for the Port Pal Container Depot Management System (CDMS). Use these to query containers, customers, movements, and finance KPIs on behalf of the signed-in user. All tools respect organization scoping and role-based access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_containers_default, get_container_default, list_customers_default, list_recent_movements_default, finance_dashboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
