
CREATE OR REPLACE FUNCTION public.category_to_gl_code(_category text, _account_type account_type)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path TO 'public'
AS $$
  SELECT CASE _category
    WHEN 'container_sale'               THEN '4030'
    WHEN 'container_sale_cogs'          THEN '5010'
    WHEN 'container_cogs'               THEN '5010'
    WHEN 'container_inventory'          THEN '1200'
    WHEN 'work_in_progress'             THEN '1220'
    WHEN 'accounts_receivable'          THEN '1100'
    WHEN 'accounts_payable'             THEN '2000'
    WHEN 'container_acquisition_payable' THEN '2010'
    WHEN 'container_acquisition_payable_adjustment' THEN '2010'
    WHEN 'cost_adjustment'              THEN CASE _account_type::text
                                              WHEN 'liability' THEN '2010'
                                              WHEN 'asset' THEN '1200'
                                              ELSE '5010' END
    WHEN 'grni'                         THEN '2100'
    WHEN 'accrued_expenses'             THEN '2100'
    WHEN 'cash'                         THEN '1000'
    WHEN 'bank'                         THEN '1010'
    WHEN 'inventory'                    THEN '1200'
    WHEN 'materials_inventory'          THEN '1210'
    WHEN 'gate_fee'                     THEN '4010'
    WHEN 'storage'                      THEN '4000'
    WHEN 'handling'                     THEN '4010'
    WHEN 'repair_revenue'               THEN '4020'
    WHEN 'conversion_revenue'           THEN '4040'
    WHEN 'lease_revenue'                THEN '4050'
    WHEN 'logistics_revenue'            THEN '4060'
    WHEN 'fuel'                         THEN '6400'
    WHEN 'tolls'                        THEN '6400'
    WHEN 'loading'                      THEN '6400'
    WHEN 'permits'                      THEN '6400'
    WHEN 'parking'                      THEN '6400'
    WHEN 'subcontractor'                THEN '6400'
    WHEN 'mileage'                      THEN '6400'
    WHEN 'truck_hire'                   THEN '6400'
    WHEN 'driver_allowance'             THEN '6400'
    WHEN 'driver_salary'                THEN '6000'
    WHEN 'repairs'                      THEN '6500'
    WHEN 'payroll'                      THEN '6000'
    WHEN 'wage_allowances'              THEN '6000'
    WHEN 'wages_payable'                THEN '2300'
    WHEN 'payroll_payment'              THEN '2300'
    WHEN 'project_labour'               THEN '5030'
    WHEN 'direct_labour'                THEN '5030'
    WHEN 'conversion_materials'         THEN '5020'
    WHEN 'input_tax'                    THEN '2210'
    WHEN 'output_tax'                   THEN '2200'
    WHEN 'rent'                         THEN '6100'
    WHEN 'utilities'                    THEN '6200'
    WHEN 'office'                       THEN '6300'
    WHEN 'bank_charges'                 THEN '6700'
    WHEN 'fx_gain_loss'                 THEN '6800'
    WHEN 'depreciation'                 THEN '6600'
    WHEN 'accumulated_depreciation'     THEN '1510'
    WHEN 'fixed_asset'                  THEN '1500'
    WHEN 'loan_principal'               THEN '2500'
    WHEN 'loan_interest_accrual'        THEN '2510'
    WHEN 'opening_balance_equity'       THEN '3900'
    WHEN 'loan_opening_balance'         THEN '3900'
    WHEN 'inventory_variance'           THEN '5920'
    WHEN 'other'                        THEN CASE _account_type::text
                                              WHEN 'revenue' THEN '4900'
                                              WHEN 'expense' THEN '6900'
                                              WHEN 'cost_of_goods' THEN '5000'
                                              ELSE NULL END
    ELSE NULL
  END;
$$;
